### ISSUE TITLE
Suddenly can't pull docker image during builds

### ISSUE THREAD

**Issue by dennmat-hurdle** [rtCamp/action-slack-notify#141] opened 2022-11-25 15:04 UTC
```
Pull down action image 'ghcr.io/rtcamp/action-slack-notify:v[2](redacted).2.0'
  /usr/bin/docker pull ghcr.io/rtcamp/action-slack-notify:v2.2.0
  Error response from daemon: Head "https://ghcr.io/v2/rtcamp/action-slack-notify/manifests/v2.2.0": Get "https://ghcr.io/token?scope=repository%[3](redacted)Artcamp%2Faction-slack-notify%3Apull&service=ghcr.io": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning: Docker pull failed with exit code 1, back off 6.273 seconds before retry.
```
This is during the dependency gathering so I can't even get it to skip I just have to remove all the slack notify stuff.

Anyway, thought I'd put this out here, because if it's not for some reason isolated to me, then other peoples' CI might be breaking on it as well.

Nothing has changed on my end at all since the last time it was successful (<12 hours ago).

Also this could be on GitHub's end and not this projects. As it's a complaint about a timeout on the response and GitHub hosts it I believe.

Thanks for building this it's been useful!

**Comment by melorthys** [comment] 2022-11-25 15:48
We couldn't even pull the container locally, I believe the problem was on rtCamp's Google Container Registry account. Could be the image is being renewed or accidentally deleted. 

The problem is appears to be fixed now.

**Closed** 2022-11-25 16:12 UTC
