### ISSUE TITLE
Support for custom action_url (pointing at specific step in the action flow) in a case of failure. 

### ISSUE THREAD

**Issue by fog1985** [rtCamp/action-slack-notify#114] opened 2021-12-15 09:41 UTC
Hi guys,
Right now it sends custom action_url equal to the action that was run. 
But in case of failure and if there were multiple steps, this URL will just lead you to the action flow. Not to the failure. 
In order to get to the failure, we will have to click on the left on the specific step that has failed. 
Hence it would be nice to set action_url to send the user directly to the failing step. And not to general flow run.

**Comment by Jolg42** [comment] 2022-01-04 16:27
I just created a related issue here, maybe it's the same as you or a bit different?
https://github.com/rtCamp/action-slack-notify/issues/116

**Comment by mrrobot47** [comment] 2022-04-13 09:45
Closing as duplicate of https://github.com/rtCamp/action-slack-notify/issues/116

**Closed by mrrobot47** 2022-04-13 09:45 UTC
