### ISSUE TITLE
Add GITHUB_URL

### ISSUE THREAD

**Issue by kotyara85** [rtCamp/action-slack-notify#86] opened 2021-05-01 20:12 UTC
Many companies are using github enterprices, so github.com url won't work for them

**Comment by mrrobot47** [comment] 2021-05-02 04:18
Closing as duplicate of https://github.com/rtCamp/action-slack-notify/issues/85

Thanks for the PR https://github.com/rtCamp/action-slack-notify/pull/87, we will be reviewing it and testing it soon.

**Closed by mrrobot47** 2021-05-02 04:18 UTC

**Comment by kotyara85** [comment] 2021-05-02 04:21
Thanks, I didn’t pay attention on 85, lol
